#!/bin/zsh

# Install basic packages
which gpg          > /dev/null || yay -S --noconfirm --quiet gpg
which wget         > /dev/null || yay -S --noconfirm --quiet wget
which htop         > /dev/null || yay -S --noconfirm --quiet htop
which gotop        > /dev/null || yay -S --noconfirm --quiet gotop
which r2           > /dev/null || yay -S --noconfirm --quiet radare2
which emacs        > /dev/null || yay -S --noconfirm --quiet emacs
which lsd          > /dev/null || yay -S --noconfirm --quiet lsd
which clang        > /dev/null || yay -S --noconfirm --quiet clang
which intelephense > /dev/null || yay -S --noconfirm --quiet nodejs-intelephense
which bat          > /dev/null || yay -S --noconfirm --quiet bat
