#!/bin/zsh

# Basic packages to install
packages=(
	'aspell'
	'aspell-en'
	'bat'
	'bandwhich'
	'bottom-bin'
	'docker'
	'docker-compose'
	'dotacat'
	'gnupg'
	'htop'
	'lsd-bin'
	'neofetch'
	'tmux'
	'wget'
)

# packages to install on a headless server
headless_packages=(
	'emacs-nox'
)

# packages to install on a desktop
desktop_packages=(
	'clang'
	'emacs'
	'hub'
	'gitflow-avh'
	'nodejs-intelephense'
	'radare2'
	'radare2-cutter'
	'rustup'
	'symfony-cli'
)

# has a display
if [[ -z $DISPLAY ]]; then
	packages+=(${headless_packages})
else
	packages+=(${desktop_packages})
fi

# Loop through the packages and install those that aren't found
for p in $packages;
	do yay -Qi ${p} &> /dev/null || yay -S --noconfirm --quiet ${p}
done
