#!/bin/zsh

# Basic packages to install
packages=(
	'bat'
	'docker'
	'docker-compose'
	'dotacat'
	'gotop'
	'gpg'
	'htop'
	'lsd'
	'neofetch'
	'rustup'
	'tmux'
	'wget'
)

# On a non headless machine
if [[ ! -z $DISPLAY ]]; then
	packages+=('clang' 'emacs' 'intelephense')
fi

# Loop through the packages and install those that aren't found
for p in $packages;
	do which ${p} > /dev/null || yay -S --noconfirm --quiet ${p}
done
