#!/bin/zsh

# Because Git submodule commands cannot operate without a work tree, they must
# be run from within $HOME (assuming this is the root of your dotfiles)
pushd "$HOME" > /dev/null

echo -e "\033[32mInit submodules\033[0m"
yadm submodule update --recursive --init > /dev/null

# Install basic packages
echo -e "\033[32mInstall packages\033[0m"
brew cask install emacs > /dev/null

# Install fonts
echo -e "\033[32mInstall fonts\033[0m"
if [[ -d "$HOME/.fonts" ]]; then
  cp "$HOME/.fonts/*" "$HOME/Library/Fonts/"
fi

# Install emacs packages
echo -e "\033[32mInstall Emacs packages\033[0m"
if [[ -d "$HOME/.emacs.d" ]]; then
  "$HOME/.emacs.d/install.sh" > /dev/null
fi

echo -e "\033[33mPlease refresh your configuration. Either:\033[0m"
echo -e "\033[33m- source ~/.zshrc\033[0m"
echo -e "\033[33m- reopen your terminal\033[0m"

# Return to the original directory
popd
