#!/bin/bash

# Because Git submodule commands cannot operate without a work tree, they must
# be run from within $HOME (assuming this is the root of your dotfiles)
pushd "$HOME"

echo "\033[33m;Init submodules\033[0m;"
yadm submodule update --recursive --init

# Source the zsh config
echo "\033[33m;Source the ZSH config\033[0m;"
source ~/.zshrc

# Install composer
echo "\033[33m;Install composer and its global packages\033[0m;"
php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
php -r "if (hash_file('SHA384', 'composer-setup.php') === '669656bab3166a7aff8a7506b8cb2d1c292f042046c5a994c43155c0be6190fa0355160742ab2e1c88d40d5be660b410') { echo 'Installer verified'; } else { echo 'Installer corrupt'; unlink('composer-setup.php'); } echo PHP_EOL;"
php composer-setup.php --install-dir=.bin
php -r "unlink('composer-setup.php');"
mv .bin/composer.phar .bin/composer
composer global install

# Return to the original directory
popd
