#!/bin/bash

# Because Git submodule commands cannot operate without a work tree, they must
# be run from within $HOME (assuming this is the root of your dotfiles)
pushd "$HOME"

echo -e "\033[32mInit submodules\033[0m"
yadm submodule update --recursive --init

# Install basic packages
echo -e "\033[32mInstall packages\033[0m"
brew cask install emacs

# Install fonts
echo -e "\033[32mInstall fonts\033[0m"
cp ~/.fonts/* ~/Library/Fonts/

# Install emacs packages
echo -e "\033[32mInstall Emacs packages\033[0m"
~/.emacs.d/install.sh

echo -e "\033[33mPlease refresh your configuration. Either:\033[0m"
echo -e "\033[33m- source ~/.zshrc\033[0m"
echo -e "\033[33m- reopen your terminal\033[0m"

# Return to the original directory
popd
